services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo_clean
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: 987654321aA
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo_clean"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=987654321aA
      - DB_NAME=odoo_clean
      - ODOO_ADMIN_PASSWORD=admin
      - ODOO_HTTP_PORT=8069
    ports:
      - "8069:8069"
    command: odoo -i web,barber_pos,clinic_patient,a_hospital,clinic_dashboard,clinic_medical_act,clinic_pos,clinic_reception,clinic_reports,clinic_validation --without-demo=all -d odoo_clean
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./custom_addons:/mnt/extra-addons
    restart: unless-stopped

volumes:
  postgres_data:
  odoo_data: